version: '3.8'

services:
  # Backend Flask service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: video-transformer-backend
    restart: unless-stopped
    volumes:
      - ./backend/downloads:/app/downloads
      - ./backend/temp:/app/temp
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - app-network

  # Frontend React service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: video-transformer-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

  # Node.js Express service
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-transformer-server
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - app-network

# Define a network
networks:
  app-network:
    driver: bridge 